- proposals/README.md
- proposals/mylesborins-GOVERNANCE.md
This documents the governance as discussed in the 2018-10-22 team meeting
Refs: https://github.com/nodejs/bootstrap/issues/2
> doc: initial governance

- README.md
- STAGING_PROCESS.md
- proposals/README.md
- proposals/TEMPLATE.md
- proposals/mylesborins-GOVERNANCE/GOVERNANCE.md
- proposals/mylesborins-GOVERNANCE/README.md
Context: On our call today, I proposed borrowing the idea of a staging process from TC-39 to our bootstrap program and policy ideas work.
This PR adds a simple staging-process.md doc for discussion, which we can iterate on and flesh out with more examples. 
Applying the proposed process, this PR would be in Stage 0. Assuming it is in the right place and there are enough +1s, we should flesh this out into a stage 1 proposal between now and the next meeting.
> Draft Staging Process

- proposals/README.md
- proposals/stage-0/stage-1/community-board-representation/README.md
TL;DR
* 1 CPC board seat
* 1 floating board seat
- allocated by CPC annually
- Requires 2 Platinum members to activate
* 1 Individual Membership board seat
- Requires 3 Platinum members and 2k Individual Members to activate
I believe the README.md has everything necessary to reach
consensus on this, thus going for stage one. It will need to be
implemented in the CPC Charter and Foundation Bylaws
> proposal: Community Board Representation Stage 1

- proposals/stage-2/CPC_CHARTER/CPC-CHARTER.md
I think the CPC Charter is too specific in how the Node.js organization is going to elect its Board member for the first year. I think this should be left to the TSC and CommComm to decide.
> cpc-charter: do not dictate how the Node.js board member is elected

- INDIVIDUAL_MEMBERSHIP.md
- PROJECT_PROGRESSION.md
- proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
- proposals/stage-3/INDIVIDUAL_MEMBERSHIP/INDIVIDUAL_MEMBERSHIP.md
- proposals/stage-3/INDIVIDUAL_MEMBERSHIP/README.md
- proposals/stage-3/PROJECT_PROGRESSION/PROJECT_PROGRESSION.md
Now that we have a name, reading OpenJS Foundation has become rather repetitive :)
Per discussion in #126, this PR uses the useful legal pattern of writing a sentence around the first instance along the lines of:
...in the OpenJS Foundation, hereinafter referred to as the "Foundation".
The scope of a statement like this is limited to each document, so there won't be spillover in the larger corpus of OpenJS Foundation governance.
> Substitute repetitions of OpenJS Foundation in docs

- CODE_OF_CONDUCT.md
Update to reflect the planned CoC process and
emails.
Once this in place we'll ask that projects refer to it
as the master CoC that applies to their project in each of the
places they refer to a CoC.
> doc: update to reflect planned CoC

- proposals/README.md
Link removed from the stage 2 category in https://github.com/openjs-foundation/bootstrap/commit/ead513e8ddc68abab97ea147c1a070979eb06a85, adding to stage 3. 👍
> Add stage 3 CPC Charter to the proposals README

- README.md
- artifacts/BOOTSTRAP_README.md
Currently still specific to Bootstrap.
Old README is archived in artifacts
Refs: https://github.com/nodejs/TSC/blob/master/README.md
> doc: update readme for CPC

- CPC-CHARTER.md
Fixes a handful of typos in the charter. No material change to the content.
> doc: fix charter typos

- README.md
This commit adds some information on where and how the CPC communicates.  It also adds some guidance on what mailing lists to join, where to find them, and what to do if there is a topic which the submitter believes is sensitive.
> Add communication channels

- README.md
https link wasn't added in #218 as their ssl certificate was invalid
it was followed up and fixed in https://github.com/jquery/esprima/issues/1975
> doc: add https for esprima website

- README.md
https link wasn't added in #218 as their ssl certificate was invalid
it was followed up and fixed in https://github.com/jerryscript-project/jerryscript/issues/2924
> doc: add https for jerryscript website

- README.md
- proposals/stage-0/TRAVEL_FUND/README.md
>The Node.js organizations that existed prior to the formation of the OpenJS foundation oversaw a monetary fund for the purpose of member and affiliate travel to, and lodging at, events related to the foundation's mission. This proposal proposes moving the management responsibilities of this fund to the Cross Project Council (CPC), and making the funds available to all members of this broader organization. Since all projects have voting representation on the CPC, the beneficiaries of the fund will jointly manage it, and the previous owners of the fund will still vote on its use.
>
>The intent is to leave the mechanics of the fund unchanged, simply moving from the purview of the Node.js project into the domain of the OpenJS Foundation, overseen by the CPC. This operation can be viewed as a …
> proposal: OpenJS Travel fund

- README.md
Brings the Interledger link in-line with other links – a website, rather than the GitHub org (removed link redirects to GitHub org)
> Update Interledger website

- PROJECT_PROGRESSION.md
Changing titles to rely on `<h4>` markup instead of `<p>` will give them automatic identifiers once the HTML is converted to markdown, which makes it possible to link directly to the subsections they're a title of.
> Using real title to improve linkability

- PROJECT_PROGRESSION.md
This is no longer accurate as #44 is closed.
> doc: remove "tbd pending outcome" from PROJECT_PROGRESSION

- CPC-CHARTER.md
Unfortunately, this wasn't caught earlier and is a change to the Charter, which has a higher bar to meet before merging.
From Governance doc
https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#merging-prs-into-this-repository
>Pull requests that change the charter of the CPC must meet the following conditions in additon to the ones listed for changing CPC governance:
>
>The text of the PR must be approved by a simple majority of the voting members.
>The text of the PR must be approved by the board.
> doc: swapping refs to TAC with CPC

- PROJECT_PROGRESSION.md
The acceptance criteria listed in the Incubation phase are actually exit criteria.
Hence adding an "Exit Criteria" subsection and moving them there.
> doc: rename acceptance criteria to graduation criteria

- GOVERNANCE.md
Adds process to allow PRs to be fast-tracked e.g. skip 72 hour rule.
This includes:
- Errata fixes.
- Editorial changes.
- Meeting minutes.
- Updates to the team lists.
- Doc Fixes.
Closes: #241
> governance: add fast-track

- .github/ISSUE_TEMPLATE/project-onboarding-checklist-template.md
- NEW_PROJECT_APPLICATION.md
- PROJECT_PROGRESSION.md
This removes the duplicated checklist in the issue template and
instead links to the checklist in the new project application
Fixes: #288
> doc: remove duplicate checklist

- CPC-CHARTER.md
This replaces the definition of "Maintainer" with "Governing Body".
There are only two instances of "Maintainer" in the charter, one of which
is in the definition of a Collaborator. This change should
make the charter better align with governance and is less ambiguous.
Closes: #289
> charter: s/maintainers/governing body

- MEMBER_EXPECTATIONS.md
This adds language about the expectation for members to express
objections or dissent as early as possible.
Closes: https://github.com/openjs-foundation/cross-project-council/issues/296
> doc: expectations for dissent / objections

- proposals/stage-0/PROJECT_EXIT_CRITERIA/README.md
addresses #96 
We will first focus on a minimal use case that _a project decided to leave the foundation_.
> Please note: There are many other use cases. We will first codify the basic criteria then expand the usecases.
Thanks @jorydotcom for the help and idea 👍
> Add project exit criteria

- .github/ISSUE_TEMPLATE/00-project-onboarding-checklist-template.md
- .github/ISSUE_TEMPLATE/99-custom-issue.md
It has been discussed in a meeting or two that there should be more than one issue template. Currently, if you are opening an issue other than a project onboarding issue, the generic/custom issue option isn't obvious. We've implemented something similar in Node in a few areas (see below). I've created these same issue templates in a personal repository so you can see what they look like in action:
- https://github.com/sometotal/leastbestbeast.com/issues/new/choose
For more issue template implementations, see the following:
- https://github.com/nodejs/node/issues/new/choose
- https://github.com/nodejs/user-feedback/issues/new/choose
> doc: building out our issue templates for better clarity

- NEW_PROJECT_APPLICATION.md
This changes the order in an attempt to surface more important
information earlier and keep longer lists of information closer
to the bottom of the application
> doc: reorganize new project application

- README.md
As discussed in the CPC meeting, this adds a number of contact points for
getting help.  Anything not covered in here, send an email to
operations@openjsf.org.
> Add a Getting Help section

- PROJECT_CHARTER_TEMPLATE.md
This is a draft charter template - a need per #207.  Wasn't sure if this should go through the proposal process since it's a document we need to unblock other issues - if that's the case LMK and I will update the PR to put this is a proposal folder. 
I used the Node TSC charter and the Kubernetes SIG Charter template as a basis. The trick is to make the charter document work for projects of different sizes, as there will be some information that will be applicable to large projects but not to the small ones. Hence, some of the sections I marked 'optional' but please do share your thoughts and comments on this!
> adds a draft charter template

- PROJECT_PROGRESSION.md
I would like to propose a modification to the process used when proposing new projects.  I believe this is a low impact change, and would like to put it up for discussion via this PR.
This commit changes the email address to which new projects proposals are sent.
Currently, new project proposals are sent directly to the mailing list where
they are also discussed.  By having the proposal first come to a person, it
provides a first-round filter to ensure all information in the application is
complete, and also ensures a clean separation between the project applicant and
the committee which is discussing the application.  The OpenJS Foundation
program manager (currently me) would then be responsible for forwarding
applications on to the (private) discussion list.
Signed-off-by: Brian Warner …
> Update contact email for new project proposals

- proposals/stage-2/CODE_OF_CONDUCT/HANDLING-REPORTS.md
Changes made: 
- s/reportee/reporter or target
- Add a link to CoC
> Changes to CoC Handling

- CPC-CHARTER.md
Issues #230 and #322 note that the links in our CPC charter to the foundations Bylaws and mission/vision statements do not work. 
We point new applicants to these documents for drafting project submissions. This PR points applicants to what I believe are the best available documents to support their drafts.
> adds missing links for bylaws and mission/vision statements

- INFRASTRUCTURE_MENU.md
This PR would add the foundation's "infrastructure menu of services" to the CPC repo. I was not 100% clear where it should ultimately live in the repo, but this PR is meant first to gather feedback and questions on the menu.
> adds infra menu PR for discussion per issue #333 & CPC conversation

- README.md
This PR is a followup from discussion in today's CPC call, where @eemeli noted this info isn't readily apparent.
Add instructions on how to contact the marketing team with requests, including
posting an item to the OpenJS Foundation blog, requesting retweets and
amplification, and getting items included in the newsletter which is
periodically sent to projects@openjsf.org.
> Add guidance on marketing outreach

- meetings/2019-10-22.md
- meetings/2019-10-29.md
- meetings/2019-11-05.md
- meetings/2019-11-12.md
- meetings/2019-11-19.md
- meetings/2019-11-26.md
- meetings/2019-12-03.md
Closes: https://github.com/openjs-foundation/cross-project-council/issues/353
Closes: https://github.com/openjs-foundation/cross-project-council/issues/381
Closes: https://github.com/openjs-foundation/cross-project-council/issues/395
Closes: https://github.com/openjs-foundation/cross-project-council/issues/401
Closes: https://github.com/openjs-foundation/cross-project-council/issues/408
Closes: https://github.com/openjs-foundation/cross-project-council/issues/412
Closes: https://github.com/openjs-foundation/cross-project-council/issues/416
> doc: add missing notes

- GOVERNANCE.md
- proposals/stage-3/TRAVEL_FUND/README.md
This should not affect the display or semantic content of either edited file.
Travis CI [warned](https://travis-ci.com/mikesamuel/cross-project-council/builds/141007449?utm_medium=notification&utm_source=email) on some lint-md errors in an unrelated PR.
> fix markdown typos to make `npm run lint-md` run clean

- LICENSE.md
This is a relic of the repo being created in the Node.js foundation org
My assumption is this should be non controversial but want a gut check.
Closes: https://github.com/openjs-foundation/cross-project-council/issues/382
> doc: update license copyright to OpenJS foundation

- CODE_OF_CONDUCT.md
This adds a copy of the text of the Contributor Covenant, version 1.4, to our [CODE_OF_CONDUCT.md](../blob/master/CODE_OF_CONDUCT.md) document. The primary reason for this is to make it clear exactly what text we're using, as the language of the upstream "version 1.4.1" has had [a few modifications](https://github.com/ContributorCovenant/contributor_covenant/commits/release/content/version/1/4/code-of-conduct.md) made to it since its release in April 2017, without an accompanying version number change.
Regarding the text itself, I've taken the contents from the [current HEAD commit](https://github.com/ContributorCovenant/contributor_covenant/blob/0b42d477/content/version/1/4/code-of-conduct.md), and filled in the [INSERT EMAIL ADDRESS] bit in its Enforcement section with "the email …
> Add a copy of the Contributor Covenant CoC text

- proposals/stage-1/CHARTER_REVIEW/README.md
- proposals/stage-1/CHARTER_REVIEW/charter_review.md
Adds a charter submission and review process to address this need for project onboarding.
> adds proposal for charter submission & review per #200

- CODE_OF_CONDUCT.md
- proposals/stage-2/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
- proposals/stage-2/CODE_OF_CONDUCT/HANDLING-REPORTS.md
[Version 2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct) of our upstream code of conduct, the [Contributor Covenant](https://www.contributor-covenant.org/), has been released. The project's [changelog](https://github.com/ContributorCovenant/contributor_covenant/blob/release/changelog) has not (yet) been updated, but by manual comparison the update appears to bring two major updates:
1. The initial pledge has an additional second part:  
> We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.
2. The "Enforcement Guidelines" section has been added, detailing actions that community leaders may take in response to infractions.
All other changes appear to be superficial.
This PR updates our references to …
> Update CoC from Contributor Covenant 1.4 to 2.0

- CODE_OF_CONDUCT.md
> doc: fix a link of Code of Conduct governance document

- meetings/2020-01-14.md
This PR publishes the meeting notes from the CPC's meeting on 2020-01-14.
Closes #444.
🎉
> Add notes from CPC Meeting on 2020-01-14

- project-resources/MEMBER_TRAVEL_FUND.md
As requested in the discussion related to moving the travel
fund to the OpenJS level.
> doc: add project specific allocation option/process

- GOVERNANCE.md
This is a governance change and needs to be open for at least 14 days OR consensus is reached in a meeting with quorum of voting members.
> doc: add new reg member to email list

- FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
Add a representative from the marketing committee to the
CoCP. The CoC will be in place for conferences and
events run by the marketing committee and handling
of CoC reports from those events may be escalated to the
CoCP so they should have a represenative.
> doc: add marketing committee rep to CoCP

- GOVERNANCE.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: clarify process that applies to WG approvals

- WORKING_GROUPS.md
Closes: https://github.com/openjs-foundation/standards/issues/58
Refs: https://github.com/openjs-foundation/standards/issues/58#issuecomment-597256462
This charter has reached consensus within the current standards team and we agreed to submit upstream in our last meeting
> doc: charter standards working group

- PROJECT_PROGRESSION.md
* Include formal IP transfers and related tooling, which cannot happen
before project has formally graduated from incubation
* Modify onboarding checklist so that IP related tasks are limited to
listing related assets and committing to post-graduation transfer.
* Use the term trademark instead of logomark.
* Update related issue template
* Create additional issue template for post-graduation checklist.
Closes #378, closes #380.
> Add post-graduation checklist

- CPC-CHARTER.md
This patch adds a section to the by laws to ensure that Voting CPC members connected to an impact or non impact project are being signed off by the current active CPC member of that project.
See also discussions in https://github.com/openjs-foundation/cross-project-council/pull/483#issuecomment-595432313
> Amendment to the by laws to ensure a sign-off between Voting CPC members

- GOVERNANCE.md
As discussed in today's CPC meeting, the governance doc specifies the nomination period when electing non-impact projects' voting CPC members, but does not specify any other related timeframes.
This year, we're not going to start voting until after the next term starts tomorrow. It would be nice if we could lock down this timeframe to more specifics to help us make sure that the current situation is not repeated in future years.
This PR suggests an initial one week period for receiving nomination issues, and then a voting period of two weeks.
> Specify non-impact voting CPC member election timeframe

- .github/PULL_REQUEST_TEMPLATE/regular-member-pull-request.md
- CPC-CHARTER.md
- GOVERNANCE.md
- README.md
I made changes as laid out in https://github.com/openjs-foundation/cross-project-council/issues/513.
I moved requirements to GOVERNANCE and reference those requirements in README and CHARTER so that we have one place for the details and if we change them in the future, we dont need to change our charter, only our governance.
**Since this PR changes both Governance and Charter, the following conditions must be met:**
Approvals from Voting Members (need 6 of 11):
> Updating requirements to become a regular member

- CPC-CHARTER.md
- GOVERNANCE.md
This is part of the work to define Board seat definitions and process.
As a first step, I've abstracted out the definition of an Active OpenJS Collaborator in our Governance.
Secondly, I've tried to capture a simple explanation of the 2 of the 3 board seats.
Also, there was a mixture of markdown link definitions, so I updated links so that they defined at the bottom of the doc.
> Board seat definitions and process

- CODE_OF_CONDUCT.md
This PR adds a list of the project-specific CoC reporting emails to our code of conduct, closing the loop for projects that wish to reference our code of conduct by providing a pointer to the URL https://code-of-conduct.openjsf.org.
> [WIP] Adds reporting emails 

- CPC-CHARTER.md
Closes #95 
As discussed in [this week's CPC meeting](https://github.com/openjs-foundation/cross-project-council/issues/594), we've done nothing to advance the Commons.js program for the past year and a half. At that time it was left with the intention of someone putting together a stage-0 proposal, but that never happened. We have, however, advanced other proposals (such as Collaboration Networks) that may provide some of the support for smaller projects as was envisioned to happen via Commons.js.
We should admit that while it was a fine idea, it's clearly not advancing as was desired. We should drop it for now, while possibly picking it back up later if a clearer, more concrete plan for it can be formed.
The thing though is that our charter mentions the Commons.js program. Therefore …
> Drop charter mention of Commons.js

- README.md
This humanizes the CPC.
It also makes it easier to find out how to contact individual members, while still leaving it up to the individual members to decide how much contact information they want to provide through their Github profile.
> Ads links to CPC members' GitHub profiles

- GOVERNANCE.md
* Adjusts the Secondary CPC Director's initial term end date to August 31, 2020 and all terms going forward will end on August 31. This is about 1 week longer than discussed in the CPC meeting on 4 August but allows us to end the term at the month boundary for easier tracking going forward.
* Adjusts the Primary CPC Director's initial term end date to February 28, 2021 and all terms going forward will end on the last day of February (28 or 29 depending on leap year). This provides the 6 month staggering the CPC agreed upon to allow for smoother transitions and knowledge transfer for new CPC directors overlapping with existing CPC directors.
* Adds a mention of the 1 year term length also applying to the Tertiary CPC Director and allows for setting the start/end dates at the time when that …
> Update term dates and lengths for CPC Directors

- README.md
I would like to nominate myself as a regular member of the CPC.
I am an active member of the [Node.js Ecosystem Security WG](https://github.com/nodejs/security-wg).
I also lead the [Vulnerability Disclosures WG](https://github.com/ossf/wg-vulnerability-disclosures) of the [Open Source Security Foundation](https://openssf.org/) and I would like to act as a liaison between the OpenJSF and the OpenSSF (both operating under the Linux Foundation).
> Add Marcin Hoppe as a regular member of the CPC

- README.md
Pending #617 and https://github.com/openjs-foundation/project-onboarding/issues/35, Fastify can be graduated to Growth.
The charter is still in review so this needs to wait for a bit more.
> Graduate fastify to growth stage

- IP_POLICY_GUIDANCE.md
The goal of this IP Policy guidance is to make it really simple for projects to comply with the Foundation's IP Policy.
This document is non-exhaustive by design. It is meant to address the most common scenarios, not every corner-case.
It is also opinionated: it favors community norms and best practices in areas where the Foundation's IP Policy provides leeway to do so.
This document is based on prior work from CNCF, available here: https://github.com/cncf/foundation/blob/master/copyright-notices.md, an earlier pull request by @brianwarner, available here: https://github.com/openjs-foundation/cross-project-council/pull/414, and community input.
Co-authored-by: Brian Warner <brian@bdwarner.com>
> Add IP Policy guidance

- proposals/stage-2/COLLABORATION_NETWORK/COLLABORATION_SPACE_PROGRESSION.md
From a discussion on the Board, I checked with OpenJS Foundation legal counsel on the preferred license, all other things being equal. While we have a number of options in the IP policy, Apache 2.0 seems to be the preferred option if there are no other reasons to choose something else.
> License preference, per discussion with legal

- CPC-CHARTER.md
- README.md
Governance changes to be landed once the Collaboration
network proposal reaches stage 3.
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: Governance changes for Collaboration Network

- PROJECT_PROGRESSION.md
The goal here is to increase transparency and help new applicants by providing them with examples of successful applications for different kinds of projects.
I'm making this a Draft PR, as I only think it makes sense publishing once we have a few more application examples than just AMP's. 
Closes https://github.com/openjs-foundation/project-status/issues/48.
> Add examples of successful applications

- CPC-CHARTER.md
Trivial changes, such as spelling or formatting updates, likely do not need board approval so long
as they do not change the overall interpretation of the CPC Charter. This change would allow the CPC
to make such trivial changes without waiting on board appproval.
> Allow trivial fixes to the charter

- README.md
No need for logo(s) at incubating stage, methinks.
> doc: Add NativeScript to incubating section in README

- README.md
Life and work has thrown a bunch of new challenges and expectations my way and I unfortunately don't have the
time to keep up with the commitments required of a regular member. It is pretty amazing that the foundation and
the CPC are in a place where I feel 100% confident in stepping back.
I'll still be around and thanks to our egalitarian governance I'll still be able to participate in all the meetings 🎉
I've moved myself to emeritus, a new section, something we've done over at Node.js that I quite like. I think
it is nice to keep track of former members.
What a wild ride this has been!
> doc: move MylesBorins to emeritus

- PROJECT_PROGRESSION.md
> Add sunsetting checklist to PROJECT_PROGRESSION.md

- TRAVEL_FUND/README.md
adds a README to the travel fund directory. PR'ing this in because I consistently try to go to this directory and actually mean to go to the file that's linked.
> doc: add README.md file to /TRAVEL_FUND

- README.md
contributing guide for ajv.js seems moved to `https://ajv.js.org/contributing/`
`https://ajv.js.org/contribute.html` is invalid. opens a 404 page.
> doc: fix ajv.js contributing guide link

- project-resources/MEMBER_TRAVEL_FUND.md
Add amount approved by board for 2021
> doc: add travel fund allocation for 2021

- README.md
With the charter approval in #750, nvm is ready to graduate incubation!
Closes https://github.com/openjs-foundation/project-status/issues/2.
> move `nvm` from Incubating to At-Large

- README.md
Mary Marchini (@mmarchini) has  asked to take an indefinite hiatus from CPC. The Node.js TSC discussed the issue and decided that I would fill out the remainder of Mary's term or until she decides to re-join the CPC.
I'm not sure what the process is for making these changes, and like an absolutely terrible council member, I am forging ahead with a pull request because it's what I know how to do.
> chore: update Node.js representative

- package-lock.json
- package.json
The remark tools are very much out of date (and are causing warnings in
the GitHub interface and the command line). This updates them to the
latest versions.
I confirmed that the linting still works by removing the newline at the
end of README.md and seeing that the same warning that it currently
generates is generated with this change.
> chore: update remark tools

- TRAVEL_FUND/2020.md
- TRAVEL_FUND/2021.md
- project-resources/MEMBER_TRAVEL_FUND.md
This is a travel fund request for participating at this year's Internationalization & Unicode Conference, and speaking there about the work being done in the Unicode MessageFormat Working Group.
I am the Foundation's representative to that working group, and a maintainer of the `messageformat` project. I have attempted to have my travel costs covered by my employer, but this is not currently possible due to their travel policy not supporting travel outside my home country (Finland).
I'm asking for 800 USD, which is an estimate of the cost of my flights (Chicago -> San Francisco -> Helsinki) and transits to and from airports. I have already made other arrangements covering my ticket for the conference, for accommodations while there, and for travel up to Chicago; this would be an extension …
> Travel fund request: Unicode Conference, 13-16 October

- CODE_OF_CONDUCT.md
Leverage the OpenJSF reporting email address rather than a dead Google form.
> Update Dojo CoC

- .github/workflows/link-checker.yml
adds a cron to the link checker that runs it nightly so we can spot issues before they're a problem in PRs
> chore: add cron to link checker

- Dates-and-Reminders.md
Moving issues we want to revisit out of the Dates-and-Reminders.md document and track them with the `cpc-quartely-review` label instead.
> Track issues outside of Dates-and-Reminders.md

- GOVERNANCE.md
I am finding that when I click on a link and then want to edit that file, I am viewing it at a commit rather than on the main branch. This makes it so that the file appears uneditable. You simply need to switch to the main branch and then can edit but it may be confusing to folks.
> Update Governance links from HEAD to main

- package-lock.json
- package.json
The real motivation here is to stop getting notified about the
vulnerable ansi-regex@6.0.0 in package-lock.json.
> chore: update remark dev dependencies

- Dates-and-Reminders.md
In today's CPC meeting, we discussed aligning a few term ends to coincide with the OpenJS World event. The thinking is that these specific roles are good roles to recruit and promote at the event.
I've also picked a somewhat arbitrary date for the CPC chair role term.
See some more notes in the following issue:
closes: #824
> Update dates for terms

- .github/workflows/link-checker.yml
Fixes #858
The link checker was working as it should, however it was not fully configured.
Links which started with the full URL `https://github.com/openjs-foundation/cross-project-council/blob/HEAD/` would check that live URL, rather than looking at the state of the build being tested.
This is fixed by configuring a URL rewrite to simply remove that starting segment of the URL.
It then looks for markdown files from the root directory.
The link checker check will fail as it highlights (correctly) some broken links.
These can be fixed with another PR.
You can validate this change locally using https://github.com/nektos/act if you so wish.
> Fix link checker using live rather than build URLs for validating

- .github/PULL_REQUEST_TEMPLATE/regular-member-pull-request.md
- .github/workflows/link-checker.yml
- CODE_OF_CONDUCT.md
- CPC-CHARTER.md
- PROJECT_PROGRESSION.md
- conduct/HANDLING_CODE_OF_CONDUCT_REPORTS.md
- governance/GOVERNANCE.md
- governance/WORKING_GROUPS.md
- governance/transfer-repo-into-org.md
- meetings/2019/2019-04-01.md
- meetings/2020/2020-09-29.md
- meetings/2020/2020-12-15.md
- meetings/2021/2021-05-25.md
- meetings/2021/2021-07-20.md
- meetings/2021/2021-08-03.md
- meetings/2022/2022-03-15.md
- meetings/2022/2022-03-29.md
- proposals/approved/SECURITY_REPORTING/README.md
- proposals/incubating/CHARTER_REVIEW/charter_review.md
Links broke probably in this PR https://github.com/openjs-foundation/cross-project-council/pull/841
Twitter status links keeps failing randomly. I have added them to skip.
> Fix broken links

- README.md
I would like to nominate myself as a regular member.
I've been an active member of the [Node.js organization](https://github.com/nodejs) for about a year now and been helping to maintain Node.js, triaging and helping users/contributors and reviewing to help things land.
I would like to participate and lend a hand to CPC and it's future.
> meta: add VoltrexMaster as a regular member

- TRAVEL_FUND/2022.md
As I have a limited budget for conference trips from my employer, I'm looking for assistance from the OpenJS Foundation for the accommodation costs (5 nights, $1583 with taxes & fees) so that I'll be able to speak on `Intl.MessageFormat` and related topics also at other conferences this year.
This PR includes a commit from PR #865, as that one adds the `TRAVEL_FUND/2022.md` file. I'll be happy to rebase this once that PR or some other adds the file to the repo.
> Travel fund request: Eemeli Aro, OpenJS World 2022

- README.md
This is a self-nomination of Rifa Achrinza as an OpenJS Foundation
(OpenJSF) Cross Project Council (CPC) Regular Member.
I have been an active member of the [LoopBack](https://loopback.io)
Technical Steering Committee (TSC), and have helped in bringing
LoopBack towards formalising a distributed, open governance model.
I've started attending the OpenJSF CPC meetings and reviewing the CPC
work and their relation to LoopBack.
With LoopBack's on-boarding as a hosted, At-Large Project under the
OpenJSF, I'd like to extend my participation be more involved in
supporting the work of the OpenJSF CPC, such as those around
supporting the projects' security posture and compliance.
see: https://github.com/loopbackio/loopback-governance/issues/26
Signed-off-by: Rifa Achrinza …
> meta: add @achrinza as a Regular Member

- TRAVEL_FUND/2022.md
Sorry for the late PR, there were some challenges with the travel fund and hence this PR is happening now. 
- Name of the event : OpenJS World 2022
- The location, dates of the event and where you will be travelling from: Austin, TX June 6-10 is the event, I shall be traveling from SF.
- The presentation you intend to give: [Standards workshop](https://sched.co/10fNK)
- The size of the stipend you wish to receive:  1500 USD.
- Estimate: 593 (Airbnb) + 753 (flight) + 154 (transport)
//cc @openjs-foundation/cpc
Signed-off-by: hemanth.hm <hemanth.hm@gmail.com>
> chore: add Hemanth HM to 2022 travel fund

- meetings/2020/2020-02-18.md
- meetings/2020/2020-02-25.md
- meetings/2020/2020-03-03.md
- meetings/2020/2020-03-10.md
- meetings/2020/2020-03-17.md
- meetings/2020/2020-03-24.md
- meetings/2020/2020-03-31.md
- meetings/2020/2020-04-07.md
- meetings/2020/2020-04-14.md
- meetings/2020/2020-04-21.md
- meetings/2020/2020-05-12.md
fixes a suite of broken links from [this run](https://github.com/openjs-foundation/cross-project-council/runs/7280370508?check_suite_focus=true). Note that the 503-ing links are not doing that, so I assume they're a hiccup.
> chore: fix broken links

- .github/workflows/link-checker.yml
this PR skips opensource.org/licenses/, which currently returns a 503 100% of the time. I'm not sure if they're just blocking traffic from Actions or what but I've seen zero runs that don't return 503 despite the links fully working for me.
> chore: add opensource.org/licenses/ to skip

- TRAVEL_FUND/2022.md
Making a travel fund request for OpenJS World 2022 to attend the conference and collaborator summit. I am hoping to help facilitate the Tooling Group sessions at the collab summit. I am also speaking at the event but virtually.
**Costs**
Hotel: Aloft Downtown Austin $1,999.44 USD
Flight: $626.25 CAD ($494.44 USD) https://www.google.com/travel/flights/s/karjSxt737ityLFk7
> Add Ian Sutherland to 2022 travel fund

- TRAVEL_FUND/2022.md
Hello,
[OpenJS Foundation has kindly agreed to cover half of my TAG travel when they nominated me in Dec 2020](https://www.w3.org/2020/12/07-tag-nominations#lv=) but Robin said I still need to follow the PR process this time, for transparency so here it is 😄 This is the second f2f TAG meeting during my term, the previous four were virtual.
Meeting dates are [July 25-28](https://github.com/w3ctag/meetings/tree/gh-pages/2022/07-London) (in 2 weeks). Because flight costs are insane right now, I cut costs by arriving on the day of the meeting and leaving on the evening of the last day instead of arriving a day before and leaving the day after.
The total trip will cost approx. $3,568, so I'm requesting **$1800** for OpenJS' half. Bocoup will cover the rest.
> Add Lea Verou - TAG meeting July 2022 to travel fund

- project-resources/INFRASTRUCTURE_MENU.md
Pretty sure that basically nobody in the CPC would recommend Travis after what's happened with them. We probably shouldn't list it here.
> chore: remove TravisCI link

- .github/workflows/link-checker.yml
- .github/workflows/linter-workflow.yml
Update the GitHub workflow actions to their latest versions and use the latest Node.js LTS release.
> meta: update GitHub workflow actions

- PROJECT_PROGRESSION.md
Clarifies that IP transfer doesn't happen at initial proposal. Closes #339.
> doc: clarify IP timing in PROJECT_PROGRESSION.md

- meetings/2021/2021-10-12.md
removes a link that's currently failing on the link checker. it's not really necessary to have this link, so I'm just entirely removing it.
> fix: remove broken link

- README.md
I was invited to add myself to the regular members list. I'm the project lead for the JSON Schema org.
I am active in the OpenJS Foundation slack, submitted PRs, and sparked discussions for the CPC. I am here to serve the open source community.
Signed-off-by: Ben Hutton <relequestual@gmail.com>
> Add Ben Hutton to regular members list

- README.md
In trying to align team membership with README, I've found two former voting members who weren't moved to regular members. Fixing that.
/cc @codebytere @boneskull
> Moving former voting mems to reg mems

- conduct/artifacts/CODE_OF_CONDUCT_PREAMBLE.md
For future tracking here's the steps taken/will be taken for the patching script:
This pull request includes the initial changes required to have a patching script for the CoC template. The patching script basically get's a commit SHA, and appends the original CoC template (available from code covenants website), and later applies the patching file (which will be included in the next pull request adding the script).
Steps needed to take to add the patching script:
1. Add a PREAMBLE file containing only the first portion of CoC
- This pull request copies the first portion, and later applies changes only required to make sense in this context. (Removing some links and adding context to CoC modifications) 
2. Add a patching script (a different pull request)
- Update the `base_url` on the …
> doc: add code of conduct prefix text

- CODE_OF_CONDUCT.md
As identified in far too many discussions, our upstream CoC is [not stable](https://github.com/EthicalSource/contributor_covenant/commits/release/content/version/2/0/code_of_conduct.md). This PR does not apply any changes to the textual content of our CoC, but adjusts the line wrapping and title levels to minimise the difference between our text and the [latest upstream text](https://raw.githubusercontent.com/EthicalSource/contributor_covenant/192bcf8016ae3733e46ff7d1285f2f57152cc195/content/version/2/1/code_of_conduct.md), v2.1.
After this is merged, it becomes somewhat easier to consider each of the four remaining parts of the diff separately:
Skipping here all the text before the `---` separator.
```diff
--- /tmp/upstream-coc.md	2023-02-08 14:22:10
+++ /tmp/openjsf-coc.md	2023-02-08 …
```
> Minimise diff between our CoC & upstream by adjusting titles & newlines

- project-resources/MEMBER_TRAVEL_FUND.md
- Update the current year fund link to point to the 2023 fund.
- List all previous funds.
> meta: update links

- .github/workflows/patch-code-of-conduct.yml
- conduct/artifacts/CODE_OF_CONDUCT_PATCH.patch
Please be aware that this is highly experimental, and might/will have some bugs. Couple of notes:
- The code, documentation, and tests live inside https://github.com/anonrig/patch-my-code-of-conduct (for now)
- When this pull request is merged, it will automatically open a pull request to update `CODE_OF_CONDUCT.md` file with the `patch` applied. 
- Before merging this pull-request, we need to get aligned with the appropriate patch file.
If we are aligned & happy on this path, I'll be happy to move the project under `openjs-foundation` organization.
> build: add patch code of conduct workflow

- .github/workflows/patch-code-of-conduct.yml
This PR fixes a mistake on the `patch_my_coc` GitHub workflow.
> build: fix CoC script `base_url` path

- .github/workflows/patch-code-of-conduct.yml
- conduct/artifacts/CODE_OF_CONDUCT_PATCH.patch
- conduct/artifacts/CODE_OF_CONDUCT_PREAMBLE.md
After we merge this pull request, an identical pull request like: https://github.com/anonrig/patch-test/pull/9 will be opened automatically by the CoC patching script.
For people who are interested in how any of these work, please take a look at [this](https://github.com/pkgjs/patch-my-code-of-conduct/tree/main/test)
> fix: update outdated CoC patch file

- CPC-CHARTER.md
Closes #1043.
As adding a vice chair role for the CPC also requires Bylaws amendment, I'm suggesting to batch it with #1055.
Please note that this pull request is against the `tobie-cpc-directors` branch (and not against `main`).
As the request is to approve batching the two issues together (#1055 and #1043), and not approving the request per se, I've added the `fast-track` label.
> Batch simplifying CPC director roles and adding a Vice Chair

- meetings/2021/2021-10-26.md
The link actually works, but I suspect newstack has implemented some bot rules that are breaking our linkchecker tooling
> fix: link breaks builds in 2021-10-26.md

- README.md
Hello everybody
Recently, I became the end-users director at the OpenJS foundation board, and I want to start being fully involved in all the CPC meetings. Please add me as a regular member; I will fully commit to my responsibilities described [here](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/COMMUNITY_BOARD_SEAT_EXPECTATIONS.md)  and will attend as many meetings as I can.
> add @edsadr as a regular member to CPC

- governance/WORKING_GROUPS.md
The CoC WG's work has been taken up by the CPC (in particular during working sessions) for a while. There's no point in keeping this defunct WG around.
_Note: the enforcement of the CoC remains with the CoC Panel, which is a different entity altogether._
Related: #1110
> Remove CoC WG

- project-resources/GITHUB_REQUESTS/2023.md
- project-resources/REQUESTING_GITHUB_RESOURCES.md
This PR adds some changes as discussed on https://github.com/openjs-foundation/cross-project-council/pull/1149#discussion_r1296375807 regarding the Markdown Sheet for GitHub Resources and minor changes on the Guidelines for Requesting Resources
> meta: updated resource request docs

- README.md
Fixes #1126 (Once merged I will update all those issues with the final selections and close them out)
1. https://github.com/openjs-foundation/cross-project-council/issues/1142 - @mcollina re-elected
2. https://github.com/openjs-foundation/cross-project-council/issues/1143 - selections reflected in readme
3. https://github.com/openjs-foundation/cross-project-council/issues/1144 - elections reflected in readme
4. https://github.com/openjs-foundation/cross-project-council/issues/1145 - elections reflected in readme
@joesepi & @tobie for visibility
> Update README.md To Reflect 2023 CPC Summer Election Results

- project-resources/GITHUB_REQUESTS/2023.md
- **Estimated monthly spend:** USD 100.00
- **Requested Features:**
- **Fund Request Champions:**
- Claudio Wunder (@ovflowd) (CPC)
- Rich Trott (@Trott) (TSC)
GitHub Codespaces for Node.js will allow Node.js contributors to build, compile and run Node.js (and other repositories, such as Node.js Website) (it will allow Pull Request updates to be done from the web, code reviews from the web, and even contributors to commit changes or implement features).
The initial idea is that:
- Only a few repositories will be enabled
- Only a few members will have access from the beginning (it will be an opt-in process)
- We will monitor the first months for usage to understand how much we spend, if we need more, how sustainable this resource can be, and how many people are interested in it.
cc …
> Requesting GitHub Codespaces for Node.js

- CPC-CHARTER.md
Closes #1054 and #1043
Assumes the Board will approve Bylaws changes similar to those drafted in  https://docs.google.com/document/d/1x-zRBQZShLMWE53J2yNlD88oudVWSj5UG8QfR2_RayI/edit?pli=1.
Summary of changes:
- Introduction of a CPC Vice Chair.
- Simplification of the various CPC Director roles by tying the number of CPC Directors to the number of active projects in the Foundation (to match how Silver Directors works), capped so that Member Directors always maintain simple majority.
For reference the Foundation currently lists 30 active projects (25 At Large and 5 Impact) and has 5 more projects in incubation. So we would just meet the threshold for adding a third CPC Director.
> Simplify CPC Board representation

- README.md
Hey folks! I guess I was not officially a member despite attending most of the meetings and events. I participate mainly in Node.js things, a bit in Express (I did the initial application for the project to join the foundation when things merged), and have been an active community member for a few years now. Happy to be a part of this great community.
> feat: Add Wes Todd as a regular member

- README.md
- community-fund/COMMUNITY_FUND_POLICY.md
This PR includes many updates to the community fund intake, review, and approval process. Highlights of this effort include
- Moving these docs into this repo, we will archive https://github.com/openjs-foundation/community-fund/ once merged
- Adding the form for intake
- Better definition of what the fund will cover
- Adding the DEI fund allocation
- Adding a new cadence and process for CPC reviews
- And more
Much thanks to @joesepi @PaulaPaul @tobie @mcollina @rginn and all the other folks in the CPC that contributed to this work.
> Fix #1147 - Adds README for new community fund process to CPC repository

- README.md
This PR removes myself as one of Electron's two CPC Voting Members, replacing with a placeholder TBD. Since I was a regular member before becoming one of Electron's Voting Members, I've put myself alongside Myles in the Emeritus section for regular members.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L131-R131): Updated the Electron project's representatives, replacing Tierney Cyren with "TBD".
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R199): Added Tierney Cyren to the list of Regular Member emeriti.
> doc: remove Tierney Cyren as Electron CPC Voting Member

- README.md
Hola! I've been active in the foundation for some time, and I'd like to become a regular member. I've been contributing to [Node.js as a Releaser and participating regularly in the Teams/WGs (Release, Security, Build, Performance, Next10..)](https://github.com/search?q=author%3Aulisesgascon+org%3Anodejs). I also recently joined the Express TC.
I've been interested in joining for a long time, but I couldn't attend the regular meetings due to my schedule. Recently, I've been participating in some CPC discussions and also in the Security Collab space. I want to participate in more initiatives within the CPC 🙌
> add Ulises Gascon as a regular member

- mentorship/2024/google-season-of-docs/README.md
This PR adds a Project Idea for 2024's Google Season of Docs tenure regarding improving Node.js's Learn material.
> chore: add Node.js's Website Learn Material as GSoD project

- README.md
Hi, I would like to request that I be added as the new CPC Voting Member for Electron. I have been a maintainer on the project for the past few years now. I'm looking forward to attending meetings and working with all of you.
> chore: add Michaela Laurencin as Electron CPC Voting Member

- PROJECT_PROGRESSION.md
Fixes #1264, note when this is merged I will update https://github.com/openjs-foundation/project-status/blob/HEAD/.github/ISSUE_TEMPLATE/00-project-onboarding-checklist-template.md
Note the project contribution agreement is the legal document that actually transfers the accounts, trademarks and limited power of attorney to the foundation.
> Fix #1264 add project contribution to checklist

- PROJECT_PROGRESSION.md
- README.md
This PR:
1. Refactors Emeritus stage into End Of Life & Archived
2. Details Annual Review Process
Much thanks to @rginn @PaulaPaul @UlisesGascon and others that contributed to this work. 
Fixes #1185
> Add Responsible End Of Life & Archiving Policies

- README.md
Hi everyone. I have finally blocked my calendar to prevent conflicts and although I'm advocating for a review of meeting times, I would like to be added to regular members, so I can participate of the CPC meetings at length -even those segments that are meant to be attended only by regular members- so I can be more effective in our goal to improve our community, standards and reach. 
I will be working with @edsadr in the ecosystem-report and I'm also part of the program committee. My current "day-work" is to make the JavaScript developer experience and tools better for developers building and deploying to one of the main public clouds and, as part of it -and vocationally- I am very involved in the OSS/JavaScript ecosystem, also acting as a liaison between the Node.js core team and the one …
> add @anfibiacreativa to regular members list

- README.md
👋 
folks looking at this PR probably know me from:
- CPC meetings
- OpenJS standards meetings
- OpenJS security meetings
- elsewhere?
🙏
> ✨ add @ctcpip to CPC members

- governance/GOVERNANCE.md
This removed a sizable amount of duplicate and/or incorrect information about our election mechanisms from GOVERNANCE.md. 
Closes #1052.
> Cleanup GOVERNANCE.md

- community-fund/COMMUNITY_FUND_POLICY.md
- Updated based on discuss in the CPC meeting today as well as follow on discussion with @tobie.
I think this might address both the concern I had as well concerns about streching out the process. It explains how approvals follow the lazy consensus process already, and extends it for rejections so that my concern about having a chance to object to those is factored in as well.
> Update community fund approval process

- README.md
- governance/GOVERNANCE.md
This PR updates the Regular member joining process to use the google form and takes into account feedback regarding the lazy consensus process outlined in #1324 
Resolves #1300
> Update CPC Regular Member Process

- community-fund/COMMUNITY_FUND_POLICY.md
- Adds a confidentiality clause
- Removes section on trip report
- Addresses the following points of issue #1258
- Mention speakers are covered through a separate fund, add link to fund
- State that the cadence of CPC review might be > monthly
- Clarify whether the fund covers attendance to event (no collab summit) where requester isn't speaking
- Mention flexibility around deadlines
- Mention trip report should be sent asap
- Moves review schedules higher up and dedupe info.
Closes #1258.
> Update to travel fund policy

- project-resources/community-health-files-guide.md
> ✨ add guide to community health files

- README.md
- project-resources/requesting_LFIT_support.md
This PR adds documentation on how to request support for LF IT managed services. @vvalderrv for visibility.
> Added information on how to request support for LF IT managed services.

- README.md
It appears that the link for infra requests has changed. Here a little patch with an update.
> Update link for `Infrastructure Request` issue template

- governance/IP_POLICY_GUIDANCE.md
Added clarifications for DCO & CLA, _hoping_ to address #387, #632, and #778
> Clarified DCO and CLA requirements

- PROJECT_PROGRESSION.md
as discussed in the CPC working session today, a slight wording change and a removal of a criterion that seemed superfluous
> update impact acceptance criteria

- README.md
cc @UlisesGascon @ctcpip did I get the Impact voting members correct for Express at the bottom of this diff? I don't recall now what is accurate
related to https://github.com/openjs-foundation/cross-project-council/issues/1378
> graduate express to impact stage in readme

- CODE_OF_CONDUCT.md
The links to the CoC Team in the code of conduct itself redirect to the CoC Policy which isn't super relevant in the case of a incident. Changing it so that it links to the info on the same page instead.
> Link to same page for CoC Team info

- PROJECT_PROGRESSION.md
In https://github.com/nodejs/TSC/pull/1650, @richardlau mentioned that we don't explain _why_ that clause is needed, so I thought we should update it here as well.
> Clarify why we are requiring at least 3 organizations in the Impact project leadership

- governance/IP_POLICY_GUIDANCE.md
Added some small examples and one clarifying line based on the conversation here: https://openjs-foundation.slack.com/archives/CS23BMK1P/p1736535381047589
> fix: copyright examples

- conduct/COC_TEAM_CHARTER.md
per CPC working session today, we identified this is missing from the CoC.  it is [listed as a requirement for projects ](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/conduct/COC_POLICY.md#delegation-to-projects) (`#6`), but missing from the CPC's own CoC
edit: it was not missing, just not in the place we were looking for it. this PR now changes the decision-making process to something more appropriate for CoC incident response
> ✨ add decision-making process for CoC

- CODE_OF_CONDUCT.md
Express has decided that the OpenJS CoC team will handle reports, and we will adhere to the CoC adopted by the CPC
ref: https://github.com/expressjs/discussions/issues/349
> docs: remove express from handling the CoC

- project-resources/SECURITY_TEMPLATE.md
Refs: https://github.com/openjs-foundation/security-collab-space/issues/290
> doc: add minimal SECURITY.md template
