openjs-foundation/cross-project-council

CODE_OF_CONDUCT.md
LICENSE.md

these were missing. Same boilerplate as other repos

doc: add license and CoC

---

meetings/2018-10-29.md

doc: add 2018-10-29 meeting notes

---

meetings/2018-11-05.md

No changes aside from adding missing link PTAL

doc: add 2018-11-05 meeting notes

---

proposals/README.md
proposals/mylesborins-GOVERNANCE/README.md

This PR relies on https://github.com/nodejs/bootstrap/pull/23
It moves the GOVERNANCE proposal to Stage 1. In this stage we are agreeing that the draft of the proposal is written in the language that will be officially adopted but that we need to reach consensus on the implementation.
The proposal also clearly outlines the expected steps to get to both stage 2 and stage 3. Please note that this proposal is an example of one that I believe can skip stage 2 and immediately go to stage three as there is not a need for board, legal, or budget approval.
For this PR please refer only to 78df381 when approving

Governance stage 1

---

meetings/2018-11-12.md

* **Recording**: https://www.youtube.com/watch?v=dIRyJ2nzYCY
* **GitHub Issue**: https://github.com/nodejs/bootstrap/issues/34

doc: add 2018-11-12 meeting notes

---

proposals/README.md
proposals/mylesborins-GOVERNANCE/README.md

As there is no need for board, budgetary, or legal approval
I believe this proposal can immediately go to stage 3
If there are no objections I'll modify this PR to do so.

doc: move governance to stage 2

---

meetings/2018-11-19.md

Refs: https://github.com/nodejs/bootstrap/issues/39

doc: add notes for 2018-11-19

---

README.md

Sorry this took so long to get up 🙂

chore: Update README.md with repo description and jargon definitions.

---

meetings/2018-11-26.md

Refs: https://github.com/nodejs/bootstrap/issues/49
Refs: https://docs.google.com/document/d/14UdfVQRda-W0e3HfIShymLfrkohQfhfKmleQbG9jHnk/edit

meetings: 2018-11-26 notes

---

meetings/2018-12-03.md

doc: 2018-12-03 meeting notes

---

proposals/TEMPLATE.md

doc: fix spelling in template

---

proposals/TEMPLATE.md

Clearer copy about how to get to stage 2 or 3

doc: update proposal template

---

proposals/README.md
proposals/stage-0/regular-town-halls/README.md

Keeping a regular cadence of community and project outreach will be important
to ensure that projects and community members feel that they are empowered to
have a voice within the foundation.

proposal: town-hall to stage 0

---

proposals/README.md
proposals/hackygolucky-EXPECTATIONS/README.md

Unresolved questions for the Expectations [proposal](https://github.com/nodejs/bootstrap/tree/master/proposals/hackygolucky-EXPECTATIONS) were added to a different README than intended. This fixes it.

Move unresolved questions

---

proposals/README.md
proposals/jorydotcom-PROJECT_PROGRESSION/PROJECT_PROGRESSION.md
proposals/jorydotcom-PROJECT_PROGRESSION/README.md

As discussed in today's merge meeting, I've taken a stab at adapting the [CNCF's Sandbox process](https://github.com/cncf/toc/blob/master/process/sandbox.md) to reflect where we seem to be heading in our [Community Drafting Doc](https://docs.google.com/presentation/d/1qUcvZz4wmQtwcWu9rWjxFNmWw5plD9-4_7mtvQvCegk/edit#slide=id.g45c3106792_4_115).
Note that this is a Stage 0 proposal and as such there are several gaps TBD & questions this will raise. But it gets some of the concepts into a PR we can have discussions about.  
cc @bnb @hackygolucky @mhdawson

[WIP] PROJECT PROGRESSION

---

meetings/2018-12-10.md

doc: 2018-12-10 meeting notes

---

meetings/2018-12-17.md

Refs: https://github.com/nodejs/bootstrap/issues/61

doc: add notes for 2018-12-17

---

meetings/2019-01-07.md

Refs: https://github.com/nodejs/bootstrap/issues/67

doc: 2019-01-07 notes

---

proposals/mdawson-cpc-charter/CPC-Charter.md
proposals/mdawson-cpc-charter/README.md

Update based on discuss in most recent bootstrap meeting
to reflect voting and regular members along with
responsibilities.

doc: update CPC membership and responsibilities

---

meetings/breakout_meetings/2019-01-14-project-progression.md

doc: add notes from session on project progression proposal

---

meetings/2019-01-21.md

Refs: https://github.com/nodejs/bootstrap/issues/79

doc: 2019-01-21 meeting notes

---

proposals/README.md
proposals/stage-2/EXPECTATIONS/EXPECTATIONS.md
proposals/stage-2/EXPECTATIONS/README.md

I believe that the major bits we didn't have consensus on have been
resolved in other proposals. This PR moves expectations to Stage 2,
so we can hand it off to the boards and hopefully move it to Stage 3
in a timely fashion.
Very minor tweaks from Stage 1, specifically removing language about
bits that we didn't currently have consensus on.
/cc @hackygolucky

proposal: expectations to stage 2

---

proposals/README.md
proposals/stage-1/individual-membership/INDIVIDUAL_MEMBERSHIP.md
proposals/stage-1/individual-membership/README.md

This refactors the current README.me to break out the bits
that are measuring the proposal VS. stuff that could be
turned into a charter or required documents to outline the program.
If we have consensus to move forward with this we should land as
stage 1 and iterate before going for stage 2.
/cc @hackygolucky

proposal: individual membership to stage 1

---

proposals/stage-1/PROJECT_PROGRESSION/PROJECT_PROGRESSION.md
proposals/stage-1/PROJECT_PROGRESSION/README.md

Lots of important updates here: 
* Adding Open Governance requirements from #74 
* Suggesting different naming schema from #44 
* Putting a finer point on the expectations for different stages
* Brining in concept of project charters (the approved version of a project proposal).

Project Progression - Stage 2

---

meetings/2019-02-11.md

Refs: https://github.com/nodejs/bootstrap/issues/98

doc: 2019-02-11 notes

---

proposals/README.md
proposals/stage-2/INDIVIDUAL_MEMBERSHIP/INDIVIDUAL_MEMBERSHIP.md
proposals/stage-2/INDIVIDUAL_MEMBERSHIP/README.md

Based on current discussion. Specific changes include
* Program to be responsibility of CPC, chartered by board.
* Program will have board seat that activates when:
- there are 3 platinum directors
- there are 2000 members registered in the program

proposal: individual membership to stage-2

---

proposals/README.md
proposals/stage-2/COMMUNITY_BOARD_REPRESENTATION/README.md

Changes based on current discussion.
Refs: https://github.com/nodejs/bootstrap/pull/102/

proposal: community board reps to stage 2

---

meetings/2019-02-25.md

Refs: https://github.com/nodejs/bootstrap/issues/107

docs: notes from 2019-02-25

---

proposals/TEMPLATE.md

Fixed typo

---

proposals/README.md
proposals/stage-3/COMMUNITY_BOARD_REPRESENTATION/README.md

Pending board approval
Pinging @mkdolan to review as foundation rep

proposals: Community Board reps to stage-3

---

meetings/2019-03-04.md

Refs: https://github.com/nodejs/bootstrap/issues/114

doc: 2019-03-04 meeting notes

---

INDIVIDUAL_MEMBERSHIP.md
PROJECT_PROGRESSION.md
proposals/stage-0/REGULAR_TOWN_HALLS/README.md
proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
proposals/stage-2/EXPECTATIONS/EXPECTATIONS.md
proposals/stage-3/COMMUNITY_BOARD_REPRESENTATION/README.md
proposals/stage-3/INDIVIDUAL_MEMBERSHIP/INDIVIDUAL_MEMBERSHIP.md
proposals/stage-3/INDIVIDUAL_MEMBERSHIP/README.md
proposals/stage-3/PROJECT_PROGRESSION/PROJECT_PROGRESSION.md

Update refernces to specify OpenJS Foundation now
that name is official.

doc: Updated references to foundation

---

PROJECTS.md

Per bootstrap meeting discussion on 3/25, adds list of current projects with their stages.

add PROJECT.md file

---

PROJECTS.md

I have confirmation from the Express team that they would like to be an at-large project.
cc @dougwilson

Make express an at-large project

---

proposals/stage-1/PROJECT_ONBOARDING/PROJECT_ONBOARDING.md
proposals/stage-1/PROJECT_ONBOARDING/README.md

Per our meeting today, this takes the initial tasks we identified in #121 and organizes them a bit as a checklist proposal. 
Reviews requested!

first pass at project onboarding checklist per #121

---

PROJECT_PROGRESSION.md

Clarified that LTS = "Long Term Support" and fixed two spelling typos.

Typo fixes and clarification

---

meetings/2019-04-01.md

Adds minutes for meeting in #136

doc: add meeting minutes for 01 April 2019 meeting

---

meetings/2019-04-15.md

Refs: https://youtu.be/rhqT6euwGr0
Refs: https://github.com/openjs-foundation/bootstrap/issues/154

doc: 2019-04-15 notes

---

meetings/2019-04-22.md
meetings/2019-04-29.md

Refs: https://github.com/openjs-foundation/bootstrap/issues/167
Refs: https://github.com/openjs-foundation/bootstrap/issues/157

meetings: remaining april meetings

---

meetings/2019-05-06.md

Refs: https://github.com/openjs-foundation/bootstrap/issues/168
Refs: https://www.youtube.com/watch?v=9L-QFZSuJFo

doc: 2019-05-06 notes

---

proposals/stage-0/COLLAB_SUMMIT/README.md
proposals/stage-1/COLLAB_SUMMIT/README.md

Ref: https://github.com/openjs-foundation/cross-project-council/issues/172#issuecomment-490561440

Added collab summit proposal

---

GOVERNANCE.md

Updates to be specific for Cross-Project-Council

doc: slight update to governance

---

CPC-CHARTER.md

This likely needs to go as an FYI to board before landing

doc: fix missing header in charter

---

README.md

Closes https://github.com/openjs-foundation/cross-project-council/issues/215 and fixes some whitespace

enh: add project links

---

README.md

doc: Add Myles Borins to Regular Members

---

README.md

add ljharb to members list

---

proposals/README.md

doc: add missing proposal to readme

---

PROJECT_PROGRESSION.md

minor cleanups, does not change anything substantial

doc: minor cleanup of project progression

---

proposals/README.md
proposals/stage-2/PROJECT_ONBOARDING/NEW_PROJECT_APPLICATION.md
proposals/stage-2/PROJECT_ONBOARDING/README.md

This draft PR is to work on getting the new projects proposal to Stage 2

proposal: move new projects to stage 2

---

meetings/2019-05-20.md
meetings/2019-06-10.md
meetings/2019-06-19.md
meetings/2019-06-26.md

Refs: https://github.com/openjs-foundation/cross-project-council/issues/227
Refs: https://github.com/openjs-foundation/cross-project-council/issues/209
Refs: https://github.com/openjs-foundation/cross-project-council/issues/197
Refs: https://github.com/openjs-foundation/cross-project-council/issues/180

doc: add notes for late May and June

---

GOVERNANCE.md

Update to add goverance related to how charters and
charter changes are approved.

doc: update governance related to charter changes

---

proposals/stage-2/PROJECT_ONBOARDING/NEW_PROJECT_APPLICATION.md

doc: clarify information must be given per repo

---

proposals/stage-2/PROJECT_ONBOARDING/NEW_PROJECT_APPLICATION.md

Maturity state terminology isn't obvious to outsiders.

doc: add link to PROJECT_PROGRESSION.md

---

STAGING_PROCESS.md

doc: it is no longer a proposal

---

CPC-CHARTER.md
README.md

incorporates language from Mike Dolan and Michael Dawson

update observers description per issue #234

---

README.md

Adds myself as a regular member ❤️

Add Tierney Cyren (@bnb) as a regular member

---

NEW_PROJECT_APPLICATION.md
proposals/README.md
proposals/stage-3/PROJECT_ONBOARDING/NEW_PROJECT_APPLICATION.md
proposals/stage-3/PROJECT_ONBOARDING/README.md

This needs to land with #165
Refs: https://github.com/openjs-foundation/cross-project-council/pull/165

proposal: move PROJECT_ONBOARDING to stage 3

---

PROJECT_PROGRESSION.md

This is part of https://github.com/openjs-foundation/bootstrap/pull/158
Specifically the changes to the already landed Project Progression document.

New project update project progression

---

meetings/2019-07-03.md
meetings/2019-07-10.md
meetings/2019-07-17.md
meetings/2019-07-23.md
meetings/2019-07-30.md

Can resolve meeting issues: #243, #250, #257, #269, #272.

doc: adding meeting notes from July

---

README.md

Adds a small bit of prose to address / direct new projects to view our project progression & new project application docs. Also fixes a typo!

add copy for new project inquiries per #261

---

GOVERNANCE.md

Refs: https://github.com/openjs-foundation/cross-project-council/pull/176

doc: add gov for first term of voting members

---

meetings/2019-08-06.md
meetings/2019-08-13.md

Refs: https://github.com/openjs-foundation/cross-project-council/issues/281
Refs: https://github.com/openjs-foundation/cross-project-council/issues/286

doc: add august 6 + 13 meeting notes

---

.gitignore
.remarkrc
.travis.yml
GOVERNANCE.md
meetings/2019-01-07.md
package-lock.json
package.json
proposals/stage-2/TRAVEL_FUND/travel-visas.md

Here is an attempt to address #233 
Check out the sample build [here](https://travis-ci.org/sendilkumarn/cross-project-council)
This completely eliminates adding any configuration on this repo. We can even create a plugin and use that for the rules configuration.

Add Markdown linter 

---

proposals/README.md

doc: add exit criteria proposal to proposal list

---

meetings/2019-08-20.md
meetings/2019-08-27.md
meetings/2019-09-03.md
meetings/2019-09-10.md
meetings/2019-09-17.md

Refs: https://github.com/openjs-foundation/cross-project-council/issues/299
Refs: https://github.com/openjs-foundation/cross-project-council/issues/311
Refs: https://github.com/openjs-foundation/cross-project-council/issues/316
Refs: https://github.com/openjs-foundation/cross-project-council/issues/320
Refs: https://github.com/openjs-foundation/cross-project-council/issues/323

doc: add missing meeting notes

---

meetings/2019-09-24.md
meetings/2019-10-01.md

doc: adding meeting notes Sep 24 and Oct 1

---

PROJECTS.md
README.md

Welcome, AMP, to incubation status!  This PR also updates the PROJECTS.md to include an incubating section with both AMP and nvm.

Add AMP to Incubating Projects, update PROJECTS.md

---

meetings/2019-10-08.md
meetings/2019-10-15.md

doc: adding meeting notes Oct 8 and 15

---

README.md

Adding myself as regular member to CPC as well as WebdriverIO to the list of growth projects.
😊

Add Christian Bromann (@christian-bromann) as regular member

---

README.md

Adding my self as a member. As being a member of the Node.js Foundation for almost 2 years. 🎉 ❤️ 
Looking forward to participating in openjs-foundation and CPC work.

added @waleedashraf as member

---

PROJECTS.md
README.md

Update README and PROJECTS to include our most recent incubating projects.

Add Electron and Fastify

---

GOVERNANCE.md

While scanning the governance document I found some minor wording issues.

Minor wording fix on governance doc

---

.github/workflows/linter-workflow.yml
package.json

Closes: https://github.com/openjs-foundation/cross-project-council/issues/317

build: add github action to run linter

---

meetings/2019-12-17.md

Closes: https://github.com/openjs-foundation/cross-project-council/issues/429

doc: dec 17 2019 notes

---

PROJECT_PROGRESSION.md

Fixes #400 per @joesepi's summary of consensus
> Champion remains point of contact through incubation. Documentation
> needs to be updated to make that clear.

Clarify that champion duties extend through incubation.

---

meetings/2020-01-07.md

Closes: https://github.com/openjs-foundation/cross-project-council/issues/436

doc: adding 2020-01-07 meeting notes

---

README.md

Hi y'all! 👋
I'd like to add myself here as a regular member. I've been a member of the Node Foundation for a few years now, and I'd love to help out with the CPC's current work. 
I'm grateful for the amazing people making this happen here. After observing today's CPC meeting, I'm excited for the chance to participate with you again. 
Thanks a million for your consideration, y'all are the best! 🙏

Add Ben Michel as regular member

---

proposals/README.md

+ Order by alphabetical
+ Add `Charter Review` to Stage 1
+ Add `Travel Fund` to Stage 2

doc: fix links in proposals index

---

meetings/2020-01-21.md
meetings/2020-01-28.md

Adding meeting notes Jan 21 and 28 2020

---

README.md

I've been a regular member of the Node.js Foundation - https://github.com/orgs/nodejs/people?query=maddhruv
for a long time (> 3 months).
I request to be added to the OpenJS Foundation as a regular member :smile:

add Dhruv (@maddhruv) as regular member

---

meetings/2020-02-04.md
meetings/2020-02-11.md

doc: adding meeting notes 2020 feb04 feb 11

---

meetings/breakout_meetings/2020-02-12-code-of-conduct.md

add meeting notes from CPC ad hoc CoC working group discussion

---

meetings/2020-02-18.md

doc: adding meeting notes 2020-02-18

---

meetings/2020-02-25.md

doc: meeting notes 2020-02-25

---

meetings/2020-02-25.md
meetings/2020-03-03.md

doc: meeting notes 2020 03-03

---

meetings/2020-03-10.md

Meeting Notes 2020-03-10

---

meetings/2020-03-17.md
meetings/2020-03-24.md
meetings/2020-03-31.md

closes: #493
closes: #500
closes: #506

doc: adding meeting notes March 17 24 31

---

meetings/2020-04-07.md

doc: meeting notes for 2020-04-07

---

meetings/2020-04-14.md
meetings/2020-04-21.md

doc: meeting notes April 14 and 21

---

.github/workflows/linter-workflow.yml

Currently install and lint were happening in a single step which was a bit confusing

tools: make action more explicit

---

mentorship/2020/google-season-of-docs/README.md

I've put together a brief proposal here for modules documentation work.
Please let me know if the structure seems about right - feedback very welcome.

Season of Docs 2020 Proposal - ES Modules

---

mentorship/2020/google-season-of-docs/README.md

This updates some of the wording for the proposal, and adds @geoffreybooth as a mentor.

Google Season of Docs - modules rewording, mentor list update

---

mentorship/2020/google-season-of-docs/README.md

Fastify would really love some help on our docs :).

Add Fastify to the google seasons of docs 2020

---

mentorship/2020/google-season-of-docs/README.md

make it clearer there are two proposals

---

meetings/2020-04-28.md
meetings/2020-05-05.md
meetings/2020-05-12.md

closes: #542
closes: #539
closes: #533

Meeting Notes 0428 0505 0512

---

WORKING_GROUPS.md

Adding Code of Conduct WG charter

---

proposals/stage-0/SECURITY_REPORTING/README.md

I forgot to add the title. This PR fixes that.

Fix title for Security Reporting proposal

---

README.md

I have been active for the past 3 months with Node website redesign as well as have been attending the CPC meetings regularly.

Add Divy as a regular member

---

README.md

Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
Looks like we missed adding this after the election closed.

doc: add reg members elected as voting members

---

README.md

All, 
I've really enjoyed coming to these meetings, learning about the work in front of this group, and putting my toe in the water by working on the Membership proposal. Would love to throw my hat in the ring as an official committee member.

Added myself to the CPC list

---

README.md

Updates our README.md to reflect the announcements at OpenJS World today.
Refs: 
- [Electron](https://twitter.com/openjsf/status/1275448367967961094)
- [AMP](https://twitter.com/openjsf/status/1275450856435941377)

feat: move AMP from Incubating to Growth and Electron from Incubating to Impact

---

COMMUNITY_BOARD_SEAT_EXPECTATIONS.md

Initial draft, community board seat

---

README.md

I've been active on Node.js for a few years, I'm starting to familiarize myself more with the work the CPC does and I would like to get more involved.

Add mmarchini as a regular member

---

README.md

Electron's CPC Voting Members

---

README.md

Adding myself as a regular member to CPC as per @joesepi's reco ❤️

add @darcyclarke as a regular member to CPC

---

README.md

Ref: https://github.com/nodejs/TSC/issues/898

Mary takes the place of Matteo

---

proposals/stage-1/SUPPORTER_PROGRAM/README.md
proposals/stage-1/SUPPORTER_PROGRAM/SUPPORTER_PROGRAM.md

Added product of discussion from the last meeting.

Supporter Program Update

---

PROJECT_PROGRESSION.md

Account for project-onboarding renaming

---

IP_POLICY_GUIDANCE.md

References https://github.com/openjs-foundation/cross-project-council/issues/657.

Add ICLA-only option to IP Policy Guidance

---

meetings/2020-08-25.md
meetings/2020-09-01.md
meetings/2020-09-08.md
meetings/2020-09-15.md
meetings/2020-09-22.md
meetings/2020-09-29.md
meetings/2020-10-06.md

sorry the meeting notes haven't been committed sooner. :/
closes: #654
closes: #652
closes: #646
closes: #638
closes: #636
closes: #631
closes: #627

meeting notes augsepoct

---

meetings/2020-10-13.md

CPC meeting notes 2020-10-13

---

meetings/2020-10-20.md

Meeting minutes 2020-10-20

---

GOVERNANCE.md

Refs: https://github.com/openjs-foundation/cross-project-council/issues/629
Add info about Director elections as agreed in discussion in
Signed-off-by: Michael Dawson <mdawson@devrus.com>

doc: add info about director elections

---

CPC-CHARTER.md

This is purely editorial and so shouldn't require board review.

Fix typo in charter

---

PROJECT_PROGRESSION.md

Clarify and add resources to the onboarding checklist.
Worth noting that this checklist is already out of sync with https://github.com/openjs-foundation/project-status/blob/master/.github/ISSUE_TEMPLATE/project-onboarding-checklist-template.md.
My suggestion would be to move this list over to the `project-status` repo and reference it from there.

Improve onboarding checklist

---

PROJECT_PROGRESSION.md

Require consent rather than 2/3 vote for emeritus

---

proposals/README.md

Move security reporting policy to approved

---

README.md

[CHORE] Broken Link Fix

---

GOVERNANCE.md

Per #745 - we were looking to add prose that made it clear current Voting members are still valid if an election was not complete in time.

Update Voting Member Term info

---

README.md

closes: #751 
closes: #752
Congrats and thank yous to @eemeli @tobie and @mhdawson! 🎉

Updating elected members

---

README.md

I changed jobs recently, so that ought to be reflected here.
I do not expect this to result in any other changes wrt my participation in OpenJSF activities.

Update affiliation for Eemeli: Vincit -> Mozilla

---

README.md

as part of https://github.com/openjs-foundation/project-status/issues/62. 
Preview from VS Code
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>

add LoopBack as incubating project

---

meetings/2021/2021-05-11.md
meetings/2021/2021-05-25.md
meetings/2021/2021-06-08.md
meetings/2021/2021-06-22.md
meetings/2021/2021-07-06.md
meetings/2021/2021-07-20.md
meetings/2021/2021-08-03.md

Closes #757 
Closes #765  
Closes #766 
Closes #768 
Closes #771 
Closes #776 
Closes #785

adds meeting minutes from May, June, & July

---

.remarkrc
CODE_OF_CONDUCT.md
CPC-CHARTER.md

Simplify CoC page

---

meetings/2021/2021-08-17.md
meetings/2021/2021-08-31.md
meetings/2021/2021-09-14.md
meetings/2021/2021-10-12.md
meetings/2021/2021-10-26.md

Closes #791 
Closes #792
Closes #797
Closes #802
Closes #806

add minutes for CPC meetings from August, September, October

---

README.md

I contribute and attend meetings on a regular basis so best to make it semi-official.

Add myself to regular members list

---

proposals/approved/SECURITY_REPORTING/README.md

This broken link is failing our PRs

Fix broken link

---

README.md

Closes #746
Help welcomed to list all of the documents and policies the CPC is working on and maintains.

List documents maintained by the CPC

---

meetings/2022/2022-03-15.md

Meeting notes: 2022-03-15

---

README.md

Minor updates to documentation to clarify some questions raised by @Relequestual in #844.

Minor update to legal-questions instructions

---

meetings/2022/2022-03-29.md

doc: add 2022-03-29 meeting notes

---

CODE_OF_CONDUCT.md

Fixes https://github.com/openjs-foundation/cross-project-council/issues/807

Fix broken local anchors

---

PROJECT_PROGRESSION.md

Fixes https://github.com/openjs-foundation/cross-project-council/issues/846

Add link to Trademark Policy re crowdfunding

---

README.md

Signed-off-by: Dylan Schiemann <dylan@dojotoolkit.org>

Update my employer on the readme

---

TRAVEL_FUND/2022.md

Traveling from: Berlin, Germany
Airfare: $1100 (estimated)
Hotel: $1537 (5/6 nights, depending on cheap flight)
Other travel (to/from the airport):  $50
Sub Total = $2687
Contribution from the employer for hotel = -$400
**Total = $2287**

Travel Fund Request @waleedashraf - OpenJS World - Austin

---

TRAVEL_FUND/2022.md

In normal years I would ask my employer to cover all of this, but I'm in an early stage startup so any assistance is appreciated.
Traveling from: Phoenix, Arizona
Airfare: $491 (actual)
Hotel: $1291 (4 nights, $1076 + est 20% taxes/fees)
Everything else: I'll cover it
Sub Total = $1782
Total = $1782
Signed-off-by: Dylan Schiemann <dylan@dojotoolkit.org>

Travel Fund Request @dylans - OpenJS World - Austin

---

governance/IP_POLICY_GUIDANCE.md

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

doc: fix broken URL anchor, grammar

---

README.md

The Linux Foundation has added a ticketing system to track requests for project and member services. This PR adds documentation around the new processes.

Update contact methods for requesting help

---

TRAVEL_FUND/2022.md

I would like to attend OpenJS World if at all possible. I'm submitting this to cover the bulkier expenses of travel (primarily hotel) since I'm currently unemployed, but I should be able to cover everything else.

chore: add Tierney Cyren to 2022 travel fund

---

TRAVEL_FUND/2022.md

My company is able to provide some support to my travel costs, but that is limited due to the stage we're at. Any support from the foundation would be gratefully received.
Flights (from UK) + Hotel: £1700 (GBP) / $2000 (USD)
I will be covering other travel costs myself.
Signed-off-by: Nick O'Leary <nick.oleary@gmail.com>

Travel Fund Request @knolleary - OpenJS World - Austin

---

project-resources/MEMBER_TRAVEL_FUND.md

closes #927 
Signed-off-by: Waleed Ashraf <waleedashraf@outlook.com>

Add Community Fund for 2022

---

TRAVEL_FUND/2022.md

- **Event**: [NodeConf EU 22](https://nodeconf.eu/) + CollabSummit
- **Location**: The Lyrath Estate, Kilkenny, Ireland, **Dates**: September 30 - October 6, **Travelling from**: São Paulo - Brazil 
- **Flight**: [SkyScanner](https://www.skyscanner.com.br/transport/flights/saoa/dub/220930/221006/config/11952-2209301605--32480-1-11154-2210011015|11154-2210061900--32480-1-11952-2210070545?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1) - $1689,50 (average from $1,571 - $1,808)
- **Transportation**: [Dublin to Killkenny](https://www.irishrail.ie/en-ie/Offer/webfares) - €18
- **Hotel**: [Kilford Arms](https://www.booking.com/Share-kg7HeM) - $280
- **Hotel**: [Jacobs Inn Hostel](https://www.booking.com/Share-uaR3oE) - $287 …

travel request - from BR to IE - NodeConf EU 22

---

README.md

updates one Electron rep to @erickzhao, removing @codebytere (thank you @codebytere <3), and updating my personal employment.

chore: update Electron reps

---

TRAVEL_FUND/2022.md

Travel Fund request for Collab Summit + NodeConfEU
Dates: 29 Sept - 6 Oct
Traveling from: Berlin
Flight: 186 USD
Hotel: 800 USD (550 + 250)
Visa: 60 USD
Local transport: 100 USD (to/from Dublin and Kilkenny to the conference venue. Hopefully this will be less.)
Event Ticket: 679 USD
Total: 1825 USD
I couldn't get funding from my employer.
I've added an extra row at the bottom with the total of all approved funds + this one. Easy to keep track of. It should be updated with every new request. If others don't agree, I can remove it.

Travel fund request for Collab Summit - Dublin

---

TRAVEL_FUND/2022.md

**Request for:** Collab Summit
**Dates:** 30th September - 3rd October
**Travelling from:** Munich
**Flight:** ~430 USD
**Hotel:** ~670 USD
**Total:** ~1110 USD
I couldn't get funding from my Employer, as they're holding unnecessary costs for now due to the Economic recession.
The member will pay all other costs like Transportation and Food. No expensing is needed.
Signed-off-by: Claudio Wunder <cwunder@gnome.org>

chore(expenses): claudio wunder - collab summit

---

TRAVEL_FUND/2022.md

Related to https://github.com/openjs-foundation/cross-project-council/pull/926
Signed-off-by: Erick Wendel <erick.workspace@gmail.com>

removing Erick Wendel's request for travel

---

TRAVEL_FUND/2022.md

**Travel Fund request for Collab Summit + NodeConfEU**
**Dates:** 1 Oct - 5 Oct
**Traveling from:** Montreal, Canada
**Flight:** 788 USD
**Hotel:** 775 USD
**Total:** 1563 USD
I couldn't get funding from my employer.
The member will pay all other costs like local transportation and food. No expensing is needed.

chore: add Ruy Adorno to 2022 travel fund

---

README.md

Signed-off-by: Abby Cabunoc Mayes <abbycabs@github.com>

Requesting to be a Regular Member

---

meetings/2021/2021-11-23.md
meetings/2021/2021-12-07.md

adding old meetings minutes from 2021

---

PROJECT_PROGRESSION.md

doc: clarify that champion cannot be applicant

---

README.md

I'm an active collaborator and contributor to the Node.js project. I'm currently focused on forming the [nodejs/performance](https://github.com/nodejs/performance) team and improving Node.js performance in general. I've attended several meetings and want to contribute more to the OpenJS Foundation.
My contributions to Node.js:
- Commits authored: https://github.com/search?q=author:anonrig+org:nodejs
- Pull requests and issues authored: https://github.com/search?q=author%3Aanonrig+org%3Anodejs&type=issues
- Reviews on pull requests in nodejs/node: https://github.com/nodejs/node/pulls?q=reviewed-by:anonrig
- Comments on pull requests and issues throughout the Node.js organization: https://github.com/search?q=commenter:anonrig+org:nodejs

meta: add @anonrig as a regular member

---

meetings/2022/2022-01-04.md
meetings/2022/2022-01-18.md
meetings/2022/2022-02-01.md
meetings/2022/2022-02-15.md
meetings/2022/2022-03-01.md
meetings/2022/2022-04-12.md
meetings/2022/2022-04-26.md
meetings/2022/2022-05-10.md
meetings/2022/2022-05-24.md
meetings/2022/2022-06-21.md
meetings/2022/2022-07-05.md
meetings/2022/2022-07-19.md
meetings/2022/2022-08-02.md
meetings/2022/2022-08-30.md
meetings/2022/2022-09-13.md
meetings/2022/2022-09-27.md
meetings/2022/2022-10-11.md
meetings/2022/2022-10-25.md
meetings/2022/2022-11-08.md

Closes: #956
Closes: #952 
Closes: #946 
Closes: #940 
Closes: #934
Closes: #929 
Closes: #921 
Closes: #915 
Closes: #909
Closes: #904 
Closes: #893 
Closes: #883 
Closes: #870 
Closes: #864 
Closes: #834 
Closes: #831 
Closes: #828 
Closes: #822 
Closes: #819

so many minutes so little time

---

README.md

I want to join the CPC as a Regular member. My goals are to contribute with Engagement and Community efforts and towards the OpenJS Foundation goals by enabling JavaScript projects and being an active voice for Internationalisation, Diversity, Accessibility and Communities.
I also plan to contribute to the high-level decision-making process and help the OpenJS Foundation in its activities. I've contributed to the Node.js project through the Web WG, i18n WG and SEA WG.
I'm also attending regular OpenJS meetings, and I want to contribute on a broader scope.
I also hope to leverage Documentation processes throughout different projects supported by the OpenJS Foundation, I've started by creating unified documentation proposals on the nodejs/next-10 repository.
**Commits authored:** …

meta: add @ovflowd as regular member

---

README.md

Update VoltrexMaster's GitHub username to the new one.

meta: update VoltrexMaster's username

---

TRAVEL_FUND/2022.md

Travel Fund request for Open Visualization Collab Summit in Madrid. 
The requested amount was for flight + hotel. The member will pay all other costs.

chore: add Xiaoji Chen to 2022 travel fund

---

meetings/2022/2022-11-22.md

add Meeting doc 2022-11-22

---

conduct/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md

Changes from meeting 2022-1213

Initial CoCP changes and email update

---

meetings/2023/2023-01-03.md

closes: #989 
Signed-off-by: Joe Sepi <sepi@joesepi.com>

doc: add meeting minutes CPC 2023-01-03

---

meetings/2023/2023-01-17.md
meetings/2023/2023-01-31.md

closes: #1001 
closes: #998 
Signed-off-by: Joe Sepi <sepi@joesepi.com>

doc: adding meeting minutes

---

meetings/2023/2023-02-14.md

closes: #1011 
Signed-off-by: Joe Sepi <sepi@joesepi.com>

doc: add meeting minutes 2023-02-14

---

PROJECT_FUND/2023.md
PROJECT_FUND/README.md
project-resources/PROJECT_FUND.md
project-resources/PROJECT_FUNDS.md

This PR introduces an initial version of the "Project Initiatives Funds".
Closes https://github.com/openjs-foundation/cross-project-council/issues/953.

feat(project-funds): add initial version of project funds

---

package-lock.json
package.json

Update the `remark-cli` developer dependency to it's latest version.
Changelog: https://github.com/remarkjs/remark/releases/tag/remark-cli%4011.0.0

deps: update remark-cli

---

meetings/2023/2023-03-14.md
meetings/2023/2023-03-28.md

March Meeting Minutes

---

conduct/artifacts/CODE_OF_CONDUCT_PREAMBLE.md

Upon request from @eemeli, this pull request reverts changes on the preamble file so that the chain of patching script is not broken.

doc: revert changes on the preamble

---

README.md

I have been participating more recurrently lately - adding my name so that I can also stick around for private sessions.
cc @joesepi

add @ruyadorno as a regular member to CPC

---

meetings/2023/2023-05-23.md

doc: CPC meeting minutes 2023-05-23

---

.github/ISSUE_TEMPLATE/ad-hoc-meeting.md

Closes https://github.com/openjs-foundation/cross-project-council/issues/1090

chore: remove default assignment

---

meetings/2023/2023-06-06.md

doc: 2023-06-06 CPC meeting minutes

---

meetings/2023/2023-06-20.md

doc: meeting minutes 2023-06-20

---

governance/GOVERNANCE.md

Add guidelines for Board updates

---

meetings/2023/2023-07-11.md

doc: CPC meeting minutes 2023-07-11.md

---

meetings/2023/2023-08-08.md

doc: add meeting minutes Aug 8

---

PROJECT_PROGRESSION.md

Resolves https://github.com/openjs-foundation/cross-project-council/issues/1026
Detail how people should indicate they are a projects representitives to join the CPC. Per https://github.com/openjs-foundation/cross-project-council/issues/1026#issuecomment-1577383503

Add detail to project progression checklist

---

meetings/2023/2023-08-22.md

doc: add meeting minutes Aug 22

---

project-resources/GITHUB_REQUESTS/2023.md

Fixes https://github.com/openjs-foundation/cross-project-council/issues/1182

fix: update url for node.js github request

---

meetings/2023/2023-10-03.md

doc: add CPC meeting minutes 2023-10-03

---

package-lock.json
package.json

- Update `remark-cli` to its new major version.
- Update the other developer dependencies to their latest versions.

chore: update developer dependencies

---

meetings/2023/2023-10-17.md

doc: add CPC meeting minutes 2023-10-17

---

meetings/2023/2023-10-31.md

doc: add CPC minutes 10-31

---

README.md

Adding Sentry (https://sentry.io) as my affiliation.

doc: update @anonrig's affiliation

---

README.md

A recent PR (#1212) had a couple issues that I'm fixing here.

Fix regular member list order and markdown formatting issue

---

meetings/2023/2023-11-28.md

doc: add meeting minutes 2023-11-28

---

meetings/2021/2021-01-05.md
meetings/2021/2021-02-16.md
meetings/2021/2021-04-13.md
meetings/2022/2022-10-11.md
proposals/approved/CPC_CHARTER/CPC-CHARTER.md

Identified in separate PR: https://github.com/openjs-foundation/cross-project-council/pull/1222

Fix broken links for linkinator check

---

README.md

Hello!
I've been joining CPC calls for the past several months and more recently have been involved in discussions of the travel fund and Code of Conduct, helping wherever I can. My company (Greyshore) has applied to become a Silver member and I plan to continue forward in the CPC and other Foundation activities. Looking forward to lending a hand-

Add Paula Paul as a regular member

---

meetings/2023/2023-12-12.md

doc: meeting minutes CPC 2023-12-12

---

README.md

I've been active in the development and maintenance of the [webpack](https://webpack.js.org/) & [ESLint](https://eslint.org/) projects for the last 3-4 years.
- Contributions to [ESLint](https://github.com/eslint/eslint/pulls?q=+is%3Apr+author%3Asnitin315+)
- Contributions to [webpack](https://github.com/webpack/webpack/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack-cli](https://github.com/webpack/webpack-cli/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack-dev-server](https://github.com/webpack/webpack-dev-server/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack.js.org](https://github.com/webpack/webpack.js.org/pulls?q=+is%3Apr+author%3Asnitin315+)

add Nitin Kumar as a regular member

---

meetings/2024/2024-01-09.md

doc: add CPC meeting minutes 2024-01-09

---

meetings/2023/2023-04-11.md

Found an old one lingering...
closes #1053

doc: add CPC meeting minutes 2023-04-11

---

meetings/2024/2024-01-23.md

doc: add CPC meeting minutes 2024-01-23

---

community-fund/COMMUNITY_FUND_POLICY.md

Add travel fund 2023 transparency report

---

README.md

Hello 👋 I would kindly request to be a regular member. I have been part to a few WG in Node.js in the past few years (Next-10, Web-Server-Framework mostly) while (co)chairing a few deep dive. I am also participating in some other projects, like Express.
I have been attending / following some of the latest CPC meetings and Working Session

Add Jean Burellier as regular member

---

README.md

Hello 👋 I would kindly request to be a regular member. 
I have been attending CPC meetings (mostly) regularly for at least a year and I hope to be able to volunteer to be more active in the committee.

chore: add Cody Zuschlag as regular member

---

Dates-and-Reminders.md
README.md

Fixes https://github.com/nodejs/TSC/issues/1504

Swap Rich with Matteo as Node.js Voting member

---

mentorship/2024/google-season-of-docs/node-2024-learn-proposal.md

After seeing relevant projects, I've noticed that we could increase the budget we're giving to our technical writer a bit.

chore: update budget for the writer

---

README.md

This PR address is [#1253] (https://github.com/openjs-foundation/cross-project-council/issues/1253#issuecomment-2007943588)
It will require the creation of the repo at https://github.com/openjs-foundation/ecosystem-report @bensternthal  your help will be needed for this.
The initial members of the space, according to the discussion on the issue, are:
- @anfibiacreativa
- @PaulaPaul 
- @tobie 
- @mhdawson 
- @italojs

Adding the collab space for the ecosystem report

---

meetings/2024/2024-04-02.md

doc: add CPC minutes 2024-04-02.md

---

Dates-and-Reminders.md

The short "positions" were not clear in my opinion.

Clarify elections calendar and roles

---

meetings/2024/2024-04-30.md

doc: CPC meeting minutes 2024-04-30

---

README.md

Im a member of the [express TC](https://github.com/orgs/expressjs/teams/express-tc) and our work there keeps intersecting w/ CPC conversations. Put me in coach!
❤️❤️❤️

add jonchurch to regular members

---

CPC-CHARTER.md

Please +1 (👍) this PR to fast-track it.

Fix broken link in charter

---

README.md

normalizes the display of CPC members and also removes duplicate entries for voting members from the regular members list

📝 clean up, deduplication, and consistent formatting of CPC members

---

community-fund/COMMUNITY_FUND_POLICY.md

@tobie this slipped away again 😄 in previous PR https://github.com/openjs-foundation/cross-project-council/pull/1338

Typo: Update COMMUNITY_FUND_POLICY.md

---

CODE_OF_CONDUCT.md

Closes #1298.
---
Missing email addresses from:

Formalize result of CoC Team selection process

---

meetings/2024/2024-07-09.md

doc: CPC meeting minutes 2024-07-09

---

governance/GOVERNANCE.md

Add policy for deleting CPC repo content

---

conduct/COC_TEAM_CHARTER.md

Document CoC Member selection

---

community-fund/COMMUNITY_FUND_POLICY.md

Added note that a person needs to be over 18.

Update COMMUNITY_FUND_POLICY.md - Add Age Requirement

---

meetings/2024/2024-10-29.md

CPC Meeting: 2024-10-29.md

---

README.md

This collaboration space is not added

Add sustainability space collaboration

---

CODE_OF_CONDUCT.md

Attempts to address the UX problem raised in https://github.com/openjs-foundation/cross-project-council/pull/1413#issuecomment-2637534752 by @nzakas

Improve visibility of CoC email address

---

README.md

This PR adds Cosmos to the list of incubating projects and removes Ajv.

Add Cosmos & Remove Ajv

---

meetings/2025/2025-02-04.md

doc: add meeting minutes 2025-02-04

---

README.md

See: https://github.com/openjs-foundation/cross-project-council/issues/1372#issuecomment-2770712525

Move NativeScript to an at-large project in the README

---

meetings/2025/2025-05-13.md

Add CPC meeting minutes 2025-05-13

---

meetings/2025/2025-02-18

Add CPC minutes 2025-02-18

---

meetings/2025/2025-06-24.md

Add CPC Meeting minutes for 2025-06-24

---

meetings/2025/2025-07-08.md

Add Minutes for July 8 CPC meeting

---

PROJECT_CHARTER_TEMPLATE.md

Add sensible defaults to project charter template

---

meetings/2025/2025-08-19.md

Add minutes for the 2025-08-19 CPC Call
